server:
  port: 8088
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopadmin?serverTimezone=UTC
    username: root
    password: 7356421
    druid:
      initial-size: 10
      max-active: 10
      min-idle: 10
    type: com.alibaba.druid.pool.DruidDataSource
#  cloud:
#    alicloud:
#      oss:
#        endpoint: https://oss-cn-shanghai.aliyuncs.com
#        bucket: bwf-shopadmin
#      access-key: LTAI5tQaeJsoZEhgP4ioyiFn
#      secret-key: SGnVgXLRtp0IySvZZPYJhuFHZQ8cgO
  redis:
    host: localhost
    port: 6379
    password: 7356421
    database: 0
    lettuce:
      pool:
        max-active: 10 #最大连接数
        min-idle: 10 #最小连接数
  cache:
    type: redis
    redis:
      key-prefix: SA_
      cache-null-values: true #是否缓存null值，解决缓存穿透
  #    热部署
  devtools:
    restart:
      #    是否启用重启
      enabled: true
      #    设置重启的目录
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**
  #   指定程序的配置文件
  #   profiles: dev
mybatis:
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    lazy-loading-enabled: true
    lazy-load-trigger-methods: toString
  type-aliases-package: com.bwf.bean
  mapper-locations: classpath:mapping/*.xml

pagehelper:
  helper-dialect: mysql

logging:
  config: classpath:log4j2/log4j2.xml
#  level:
#    com.bwf.mapper: debug

